[2021-10-17 15:57:31,311] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-07T00:00:00+00:00 [queued]>
[2021-10-17 15:57:31,317] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-07T00:00:00+00:00 [queued]>
[2021-10-17 15:57:31,317] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-10-17 15:57:31,318] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-10-17 15:57:31,318] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-10-17 15:57:31,338] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-07T00:00:00+00:00
[2021-10-17 15:57:31,341] {standard_task_runner.py:52} INFO - Started process 11914 to run task
[2021-10-17 15:57:31,347] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-07T00:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfq8d3lug', '--error-file', '/tmp/tmpdgzcub7u']
[2021-10-17 15:57:31,348] {standard_task_runner.py:77} INFO - Job 44: Subtask is_api_available
[2021-10-17 15:57:31,439] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-07T00:00:00+00:00 [running]> on host airflowvm
[2021-10-17 15:57:31,561] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-07T00:00:00+00:00
[2021-10-17 15:57:31,561] {http.py:101} INFO - Poking: api/
[2021-10-17 15:57:31,565] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-10-17 15:57:31,566] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-10-17 15:57:31,946] {base.py:243} INFO - Success criteria met. Exiting.
[2021-10-17 15:57:31,957] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200107T000000, start_date=20211017T155731, end_date=20211017T155731
[2021-10-17 15:57:31,998] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-17 15:57:32,008] {local_task_job.py:151} INFO - Task exited with return code 0
